//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photo.Resources.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Photo.Resources.Email.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SystemReference] Thank you for purchasing Cartoonkart Voucher.
        /// </summary>
        public static string AddOrderConfirmationSubject {
            get {
                return ResourceManager.GetString("AddOrderConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team,&lt;br/&gt;
        ///We have got a ticket from website, please login and replay to customer ASAP.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///Regards,&lt;br/&gt;
        ///Administrator.
        /// </summary>
        public static string NotifyComplaint {
            get {
                return ResourceManager.GetString("NotifyComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team,&lt;br/&gt;
        ///We have got an order from website, however the page is not able to send the mail to customer. &lt;br/&gt;Please send an acknowledgement mail that we have received the order.&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///[Details]&lt;br/&gt;&lt;br/&gt;
        ///Regards,&lt;br/&gt;
        ///Administrator.
        /// </summary>
        public static string NotifyPurchaseError {
            get {
                return ResourceManager.GetString("NotifyPurchaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotifyPurchaseErrorSubject {
            get {
                return ResourceManager.GetString("NotifyPurchaseErrorSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        /// &lt;head&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Basics */
        ///    .ReadMsgBody,.ExternalClass{width:100%;background-color:#f7f7f7}
        ///    .ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.Externa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderAcknowledgement {
            get {
                return ResourceManager.GetString("OrderAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        /// &lt;head&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Basics */
        ///    .ReadMsgBody,.ExternalClass{width:100%;background-color:#f7f7f7}
        ///    .ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div,br,strong br,b br,em br,i br{line-height:100%}    
        ///    body{-webkit-text-size-adjust:none;-ms [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catoonkart : Order summary.
        /// </summary>
        public static string OrderConfirmationSubject {
            get {
                return ResourceManager.GetString("OrderConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        /// &lt;head&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Basics */
        ///    .ReadMsgBody,.ExternalClass{width:100%;background-color:#f7f7f7}
        ///    .ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.Externa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SendClearImageRequestBody {
            get {
                return ResourceManager.GetString("SendClearImageRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SystemReference] Clear Image Required.
        /// </summary>
        public static string SendClearImageRequestSubject {
            get {
                return ResourceManager.GetString("SendClearImageRequestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        /// &lt;head&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Basics */
        ///    .ReadMsgBody,.ExternalClass{width:100%;background-color:#f7f7f7}
        ///    .ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.Externa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SendImageToCustomerDraftBody {
            get {
                return ResourceManager.GetString("SendImageToCustomerDraftBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        /// &lt;head&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Basics */
        ///    .ReadMsgBody,.ExternalClass{width:100%;background-color:#f7f7f7}
        ///    .ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.Externa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SendImageToCustomerPreviewBody {
            get {
                return ResourceManager.GetString("SendImageToCustomerPreviewBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SystemReference] Cartoonkart Order for [Name].
        /// </summary>
        public static string SendImageToCustomerPreviewSubject {
            get {
                return ResourceManager.GetString("SendImageToCustomerPreviewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear [Artist],
        ///
        ///Please find the attached image. 
        ///&lt;br/&gt;
        ///&lt;br/&gt;
        ///[SpecialInstruction].
        /// </summary>
        public static string SendOrderToArtistBody {
            get {
                return ResourceManager.GetString("SendOrderToArtistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SystemReference] [Product].
        /// </summary>
        public static string SendOrderToArtistSubject {
            get {
                return ResourceManager.GetString("SendOrderToArtistSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        /// &lt;head&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///    /* Basics */
        ///    .ReadMsgBody,.ExternalClass{width:100%;background-color:#f7f7f7}
        ///    .ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div,br,strong br,b br,em br,i br{line-height:100%}    
        ///    body{-webkit-text-size-adjust:none;-ms [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeMail {
            get {
                return ResourceManager.GetString("WelcomeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Catoonkart.
        /// </summary>
        public static string WelcomeSubject {
            get {
                return ResourceManager.GetString("WelcomeSubject", resourceCulture);
            }
        }
    }
}
