//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photo.Resources.PageLink {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageLink {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageLink() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Photo.Resources.PageLink.PageLink", typeof(PageLink).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Core/ChangePassword.aspx?ReturnURL=[ReturnURL].
        /// </summary>
        public static string ChangePasswordPageWithReturnURL {
            get {
                return ResourceManager.GetString("ChangePasswordPageWithReturnURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Is/ACookieMonster.html.
        /// </summary>
        public static string CookiesNotAllowedPage {
            get {
                return ResourceManager.GetString("CookiesNotAllowedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Business/Default.aspx.
        /// </summary>
        public static string DefaultPage {
            get {
                return ResourceManager.GetString("DefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resource/Pages/Preview/Default.aspx?BookingID=[BookingID]&amp;PurchaseID=[PurchaseID].
        /// </summary>
        public static string DownloadPreviewPage {
            get {
                return ResourceManager.GetString("DownloadPreviewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Default.aspx.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;[MessageType] message&quot;&gt;
        ///   &lt;p&gt;[MessageText]&lt;/p&gt;
        ///  &lt;/div&gt;.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Product/Default.aspx.
        /// </summary>
        public static string ProductDetailsPage {
            get {
                return ResourceManager.GetString("ProductDetailsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Product/[ProductDetailsLink].[ProductPropertyID].aspx.
        /// </summary>
        public static string ProductDetailsPageFriendlyUrl {
            get {
                return ResourceManager.GetString("ProductDetailsPageFriendlyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Product/Register.aspx.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resource/Pages/SEM/Default.aspx.
        /// </summary>
        public static string SEMPage {
            get {
                return ResourceManager.GetString("SEMPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode=[mode]&amp;args=[args].
        /// </summary>
        public static string SEMPageQuerystring {
            get {
                return ResourceManager.GetString("SEMPageQuerystring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Login.aspx.
        /// </summary>
        public static string SignInPage {
            get {
                return ResourceManager.GetString("SignInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Login.aspx?ReturnUrl=[ReturnUrl].
        /// </summary>
        public static string SignInPageWithReturnUrl {
            get {
                return ResourceManager.GetString("SignInPageWithReturnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SignOut.aspx.
        /// </summary>
        public static string SignOutPage {
            get {
                return ResourceManager.GetString("SignOutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Unauthorized.aspx.
        /// </summary>
        public static string UnauthorizedPage {
            get {
                return ResourceManager.GetString("UnauthorizedPage", resourceCulture);
            }
        }
    }
}
