//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photo.Resources.Repository {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Repository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Repository() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Photo.Resources.Repository.Repository", typeof(Repository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string FareRuleContentFolderLevels {
            get {
                return ResourceManager.GetString("FareRuleContentFolderLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DocumentStorageLocation]\WorkFile\.
        /// </summary>
        public static string FareRuleContentStoragePath {
            get {
                return ResourceManager.GetString("FareRuleContentStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string FareRuleStaticContentMaximumIDLeftPadding {
            get {
                return ResourceManager.GetString("FareRuleStaticContentMaximumIDLeftPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GeoIPDatabaseStorageLocation].
        /// </summary>
        public static string GeoIPDatabasePath {
            get {
                return ResourceManager.GetString("GeoIPDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.xml.
        /// </summary>
        public static string HotelPropertyItemStaticContentFile {
            get {
                return ResourceManager.GetString("HotelPropertyItemStaticContentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DocumentStorageLocation]\HotelPropertyItem\.
        /// </summary>
        public static string HotelPropertyItemStaticContentStoragePath {
            get {
                return ResourceManager.GetString("HotelPropertyItemStaticContentStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.txt.
        /// </summary>
        public static string HotelPropertyStaticContentFile {
            get {
                return ResourceManager.GetString("HotelPropertyStaticContentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DocumentStorageLocation]\HotelProperty\.
        /// </summary>
        public static string HotelPropertyStaticContentStoragePath {
            get {
                return ResourceManager.GetString("HotelPropertyStaticContentStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string HotelStaticContentFolderLevels {
            get {
                return ResourceManager.GetString("HotelStaticContentFolderLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.xml.
        /// </summary>
        public static string HotelStaticContentImageXML {
            get {
                return ResourceManager.GetString("HotelStaticContentImageXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string HotelStaticContentMaximumIDLeftPadding {
            get {
                return ResourceManager.GetString("HotelStaticContentMaximumIDLeftPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DocumentStorageLocation]\Payment\.
        /// </summary>
        public static string PaymentAttachmentStoragePath {
            get {
                return ResourceManager.GetString("PaymentAttachmentStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DocumentStorageLocation]\Reseller\.
        /// </summary>
        public static string ResellerLogoStoragePath {
            get {
                return ResourceManager.GetString("ResellerLogoStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DocumentStorageLocation]\Service\.
        /// </summary>
        public static string ServiceAttachmentStoragePath {
            get {
                return ResourceManager.GetString("ServiceAttachmentStoragePath", resourceCulture);
            }
        }
    }
}
